import type { SOP } from '../types';

export const MOCK_SOPS: SOP[] = [
  {
    id: '1',
    title: 'Emergency Maintenance Request',
    category: 'Operations',
    tags: ['Urgent', 'After-Hours'],
    lastUpdated: 'Updated 2 days ago',
    overview: 'Handle emergency maintenance requests that require immediate attention, including water leaks, heating/cooling failures, and electrical issues.',
    steps: [
      {
        title: 'Receive and log the emergency request',
        text: 'Log in the property management system under Work Orders → Emergency. Include unit number, time received, and nature of issue.',
        script: 'Portal: [https://portal.example.com]\nWork Orders → New → Emergency\n\nUnit #: ___\nIssue: ___\nReported by: ___\nTime received: ___',
      },
      { title: 'Assess severity and safety risks', text: 'Determine if the issue poses immediate danger (gas leak, flood, no heat in winter). If yes, contact emergency services first.' },
      { title: 'Dispatch maintenance technician', text: 'Contact on-call technician from the emergency roster. Provide unit number, issue description, and any safety notes.' },
      { title: 'Notify affected residents', text: 'If the issue impacts neighboring units (e.g., water shutoff), notify them via email and door notice.' },
      { title: 'Document resolution', text: 'Update the work order with time of resolution, work performed, parts used, and any follow-up needed.' },
      { title: 'Follow up within 24 hours', text: 'Call or email the resident to confirm the issue is fully resolved and document their response.' },
    ],
    edgeCases: [
      { title: 'After-hours request', description: 'Use emergency contact list. Document overtime authorization.' },
      { title: 'Resident unreachable', description: 'Leave voicemail, send email, and use emergency key if safety concern.' },
    ],
    escalation: { when: 'If issue requires more than $1,000 in repairs or poses immediate safety risk', who: 'Regional Manager (555-0100)' },
    contacts: [
      { role: 'Maintenance Lead', name: 'Mike Chen', department: 'Operations', description: 'After-hours emergency coordination' },
      { role: 'Property Manager', name: 'Sarah Johnson', department: 'Management', description: 'Budget approval over $500' },
    ],
    referenceMaterials: [
      { title: 'Emergency contact list', fileUrl: '/files/emergency-contacts.pdf' },
      { title: 'Maintenance log template', fileUrl: '/files/maintenance-log.xlsx' },
    ],
  },
  {
    id: '2',
    title: 'Resident Move-In Process',
    category: 'Leasing',
    tags: ['Onboarding', 'Inspection'],
    lastUpdated: 'Updated 1 week ago',
    overview: 'Complete move-in process for new residents, including unit inspection, key handoff, and orientation.',
    steps: [
      { title: 'Confirm move-in date and time', text: 'Contact resident 48 hours in advance to confirm date, time, and any special requirements.' },
      { title: 'Complete pre-move-in inspection', text: 'Walk the unit with the inspection checklist. Document condition of all rooms, fixtures, and appliances.' },
      { title: 'Prepare welcome packet', text: 'Assemble keys, parking passes, amenity access cards, community guide, and emergency contact sheet.' },
      { title: 'Conduct walk-through with resident', text: 'Walk the unit together documenting any existing damage. Take timestamped photos.' },
      { title: 'Review lease terms and community rules', text: 'Cover quiet hours, parking rules, pet policy, maintenance request process, and emergency procedures.' },
      { title: 'Provide management contact info', text: 'Share office hours, maintenance request portal, and after-hours emergency number.' },
      { title: 'Collect signed move-in inspection form', text: 'Have resident sign the inspection form. Upload to their file in the property management system.' },
    ],
    edgeCases: [
      { title: 'Unit not ready', description: 'Offer temporary accommodation or rent concession. Document in lease.' },
      { title: 'Resident disputes condition', description: 'Take photos, get resident signature, escalate to manager.' },
    ],
    escalation: { when: 'If resident refuses to sign inspection form or disputes unit condition', who: 'Leasing Manager (555-0101)' },
    contacts: [
      { role: 'Leasing Manager', name: 'Tom Rodriguez', department: 'Leasing', description: 'Move-in disputes and concessions' },
      { role: 'Legal Counsel', name: 'Jennifer Park', department: 'Legal', description: 'Lease agreement modifications' },
    ],
    referenceMaterials: [
      { title: 'Move-in checklist', fileUrl: '/files/move-in-checklist.pdf' },
      { title: 'Unit inspection form', fileUrl: '/files/unit-inspection.pdf' },
    ],
  },
  {
    id: '3',
    title: 'Rent Payment Late Fee Application',
    category: 'Finance',
    tags: ['Billing', 'Collections'],
    lastUpdated: 'Updated 3 days ago',
    overview: 'Process late rent payments and apply late fees per lease terms, including grace period verification and payment plan options.',
    steps: [
      { title: 'Verify grace period has expired', text: 'Check the lease for the specific grace period (typically 5 business days). Confirm the payment is outside the window.' },
      { title: 'Calculate late fee amount', text: 'Apply the fee per the lease agreement. Standard is $50 + $10/day after day 10.' },
      {
        title: 'Post late fee to resident account',
        text: 'Add the charge in the billing system under Charges → Late Fee.',
        script: 'Billing → Resident Account → Add Charge\nType: Late Fee\nAmount: $___\nEffective Date: ___\nLease Reference: ___',
      },
      { title: 'Send late payment notice', text: 'Generate and send the standard late payment notice via email and physical mail.' },
      { title: 'Document communication', text: 'Log all resident communications regarding the late payment in the system notes.' },
      { title: 'Offer payment plan if eligible', text: 'For residents with hardship, offer a structured payment plan. Requires manager approval for plans over 60 days.' },
    ],
    edgeCases: [
      { title: 'First-time late payment', description: 'May waive fee at manager discretion. Document the waiver reason.' },
      { title: 'Partial payment received', description: 'Apply payment to oldest balance first. Late fee still applies to remaining rent balance.' },
    ],
    escalation: { when: 'If rent is 30+ days past due or resident is unresponsive after 3 attempts', who: 'Collections Coordinator (555-0102)' },
    contacts: [
      { role: 'Accounting Manager', name: 'Lisa Wang', department: 'Finance', description: 'Fee waivers and payment plan approval' },
    ],
    referenceMaterials: [
      { title: 'Late fee schedule', fileUrl: '/files/late-fee-schedule.pdf' },
    ],
  },
  {
    id: '4',
    title: 'Noise Complaint Resolution',
    category: 'Resident Support',
    tags: ['Complaints', 'Community'],
    lastUpdated: 'Updated 5 days ago',
    overview: 'Address noise complaints from residents in a fair and timely manner while maintaining community standards.',
    steps: [
      { title: 'Log the complaint', text: 'Record the complainant unit, offending unit, date, time, and nature of noise in the complaint system.' },
      { title: 'Verify quiet hours policy', text: 'Check community rules for quiet hours (typically 10 PM–8 AM weekdays, 11 PM–9 AM weekends).' },
      { title: 'Contact the offending resident', text: 'Call or visit the unit. Explain the complaint (without identifying the complainant) and remind them of community rules.' },
      { title: 'Issue written notice if needed', text: 'For repeat offenses, send the standard noise violation notice with a copy to their file.' },
      { title: 'Follow up with complainant', text: 'Contact the original complainant within 48 hours to confirm the issue has been resolved.' },
    ],
    edgeCases: [
      { title: 'Ongoing construction noise', description: 'Check permitted construction hours. Notify affected residents of expected duration.' },
      { title: 'Safety concern (domestic dispute)', description: 'Do not approach unit. Call 911 immediately. Document incident.' },
    ],
    escalation: { when: 'If noise persists after two written warnings or involves safety concern', who: 'Community Manager (555-0103)' },
    contacts: [
      { role: 'Community Manager', name: 'David Kim', department: 'Resident Support', description: 'Repeat violations and lease enforcement' },
    ],
    referenceMaterials: [
      { title: 'Noise violation notice template', fileUrl: '/files/noise-violation.pdf' },
      { title: 'Community rules handbook', fileUrl: '/files/community-rules.pdf' },
    ],
  },
  {
    id: '5',
    title: 'Package Delivery Management',
    category: 'Operations',
    tags: ['Mailroom', 'Deliveries'],
    lastUpdated: 'Updated 1 day ago',
    overview: 'Manage package deliveries for residents including logging, notification, and pickup procedures.',
    steps: [
      { title: 'Receive and scan packages', text: 'Scan each package barcode into the package management system. Verify resident name and unit number.' },
      { title: 'Log package in system', text: 'Enter carrier, tracking number, and package size. Assign a locker or shelf location.' },
      { title: 'Notify resident', text: 'System automatically sends email/text notification with pickup instructions and location.' },
      { title: 'Process pickup', text: 'Verify resident ID or unit number. Have them sign the digital pickup log. Release the package.' },
      { title: 'Handle unclaimed packages', text: 'After 7 days, send a reminder notice. After 14 days, attempt return to sender.' },
    ],
    edgeCases: [
      { title: 'Damaged package on arrival', description: 'Photograph damage before accepting. Note condition in system. Notify resident immediately.' },
      { title: 'Package for former resident', description: 'Mark as "return to sender" and place in outgoing mail.' },
    ],
    escalation: { when: 'If package is reported stolen or carrier disputes delivery', who: 'Operations Manager (555-0104)' },
    contacts: [
      { role: 'Mailroom Coordinator', name: 'Ana Ramirez', department: 'Operations', description: 'Daily mailroom operations' },
    ],
    referenceMaterials: [],
  },
  {
    id: '6',
    title: 'Lease Renewal Outreach',
    category: 'Leasing',
    tags: ['Retention', 'Renewals'],
    lastUpdated: 'Updated 1 week ago',
    overview: 'Proactively contact residents approaching lease expiration to discuss renewal options and retention incentives.',
    steps: [
      { title: 'Pull expiring leases report', text: 'Run the "Leases Expiring in 90 Days" report from the property management system on the 1st of each month.' },
      { title: 'Review renewal pricing', text: 'Check approved rent increase schedule. Note any market adjustments or retention offers available.' },
      {
        title: 'Send initial renewal offer',
        text: 'Email the renewal offer letter 90 days before expiration.',
        script: 'Subject: Your Lease Renewal at Parkmerced\n\nDear [Resident Name],\n\nYour current lease expires on [Date]. We\'d love to have you stay! Here are your renewal options:\n\n• 12-month renewal: $[amount]/mo\n• Month-to-month: $[amount]/mo\n\nPlease reply or visit the leasing office to discuss.',
      },
      { title: 'Follow up at 60 days', text: 'If no response, call the resident directly. Document the conversation outcome.' },
      { title: 'Process renewal or notice to vacate', text: 'If renewing, generate the new lease and schedule signing. If vacating, begin turnover planning.' },
      { title: 'Update system records', text: 'Update lease dates, new rent amount, and any concession codes in the property management system.' },
    ],
    edgeCases: [
      { title: 'Resident requests concession', description: 'Refer to approved concession matrix. Manager approval needed for anything beyond standard offers.' },
    ],
    escalation: { when: 'If resident threatens to leave and is a high-value retention target', who: 'Leasing Director (555-0105)' },
    contacts: [
      { role: 'Leasing Director', name: 'Maria Santos', department: 'Leasing', description: 'Retention strategy and special offers' },
    ],
    referenceMaterials: [
      { title: 'Renewal offer letter template', fileUrl: '/files/renewal-letter.docx' },
      { title: 'Rent increase schedule', fileUrl: '/files/rent-schedule.pdf' },
    ],
  },
  {
    id: '7',
    title: 'Parking Space Transfer',
    category: 'Operations',
    tags: ['Parking', 'Transfers'],
    lastUpdated: 'Updated 4 days ago',
    overview: 'Process resident requests to transfer, add, or release parking spaces including permit updates and billing adjustments.',
    steps: [
      { title: 'Receive transfer request', text: 'Have resident complete the parking transfer request form with current and desired space details.' },
      { title: 'Check availability', text: 'Search the parking database for open spaces matching the request (covered, uncovered, EV-charging, etc.).' },
      {
        title: 'Update parking assignment',
        text: 'Assign the new space in the system and deactivate the old permit.',
        script: 'Parking → Manage Assignments\nResident: [Name]\nOld Space: [#] → Deactivate\nNew Space: [#] → Activate\nEffective Date: ___',
      },
      { title: 'Issue new parking permit', text: 'Print or activate the digital permit for the new space. Collect old permit if physical.' },
      { title: 'Adjust billing', text: 'Update monthly parking charge if the new space has a different rate. Prorate for partial months.' },
      { title: 'Notify security', text: 'Email the updated parking roster to the security team with effective date.' },
    ],
    edgeCases: [
      { title: 'No matching spaces available', description: 'Add resident to the waitlist. Provide estimated wait time based on historical turnover.' },
      { title: 'ADA accommodation request', description: 'Prioritize accessible space assignment. Document the accommodation request.' },
    ],
    escalation: { when: 'If resident has ADA accommodation needs or disputes towing', who: 'Operations Director (555-0106)' },
    contacts: [
      { role: 'Parking Coordinator', name: 'James Wright', department: 'Operations', description: 'Space assignments and permits' },
    ],
    referenceMaterials: [
      { title: 'Parking transfer form', fileUrl: '/files/parking-transfer.pdf' },
      { title: 'Parking rate sheet', fileUrl: '/files/parking-rates.pdf' },
    ],
  },
  {
    id: '8',
    title: 'Vendor Invoice Processing',
    category: 'Finance',
    tags: ['Accounts Payable', 'Vendors'],
    lastUpdated: 'Updated 2 days ago',
    overview: 'Receive, verify, and process vendor invoices for property services including maintenance, landscaping, and utilities.',
    steps: [
      { title: 'Receive and log invoice', text: 'Scan or download the invoice. Enter into the AP system with vendor name, invoice number, and amount.' },
      { title: 'Match to purchase order', text: 'Verify the invoice matches an approved PO. Check quantities, rates, and total against the order.' },
      { title: 'Obtain manager approval', text: 'Route invoices over $500 for manager approval. Under $500 can be approved by the AP clerk.' },
      {
        title: 'Enter payment in system',
        text: 'Schedule the payment per vendor terms (Net 30, Net 15, etc.).',
        script: 'AP → New Payment\nVendor: ___\nInvoice #: ___\nAmount: $___\nPO #: ___\nPayment Terms: ___\nScheduled Date: ___',
      },
      { title: 'File documentation', text: 'Attach the invoice, PO, and approval to the payment record. File physical copies if required.' },
    ],
    edgeCases: [
      { title: 'Invoice without PO', description: 'Flag for review. Requires department head approval before processing.' },
      { title: 'Duplicate invoice', description: 'Verify against payment history. Contact vendor if duplicate is confirmed.' },
    ],
    escalation: { when: 'If invoice exceeds $10,000 or vendor disputes payment', who: 'Controller (555-0107)' },
    contacts: [
      { role: 'AP Supervisor', name: 'Karen Lee', department: 'Finance', description: 'Invoice disputes and vendor relations' },
    ],
    referenceMaterials: [],
  },
  {
    id: '9',
    title: 'After-Hours Lockout Assistance',
    category: 'Resident Support',
    tags: ['After-Hours', 'Keys'],
    lastUpdated: 'Updated 3 days ago',
    overview: 'Assist residents who are locked out of their unit outside of regular office hours.',
    steps: [
      { title: 'Verify resident identity', text: 'Confirm full name, unit number, and one piece of photo ID. Cross-reference with the resident database.' },
      { title: 'Attempt remote unlock', text: 'If the building uses smart locks, try remote unlock via the access control system.' },
      { title: 'Dispatch on-call staff', text: 'If remote unlock is unavailable, contact the on-call maintenance technician to provide physical key access.' },
      { title: 'Document the lockout', text: 'Log the incident with date, time, unit, staff involved, and resolution method.' },
      { title: 'Recommend key replacement', text: 'If resident has lost their key, schedule a lock rekey during business hours and issue a temporary key.' },
    ],
    edgeCases: [
      { title: 'Resident cannot provide ID', description: 'Require secondary verification (lease details, security question). Do not grant access without positive identification.' },
    ],
    escalation: { when: 'If identity cannot be verified or there is suspected unauthorized access', who: 'Security Supervisor (555-0108)' },
    contacts: [
      { role: 'On-Call Technician', name: 'Carlos Mendez', department: 'Operations', description: 'After-hours key access' },
    ],
    referenceMaterials: [
      { title: 'Lockout procedure card', fileUrl: '/files/lockout-procedure.pdf' },
    ],
  },
  {
    id: '10',
    title: 'Pet Registration and Policy Enforcement',
    category: 'Resident Support',
    tags: ['Pets', 'Policy'],
    lastUpdated: 'Updated 1 week ago',
    overview: 'Register resident pets, collect pet deposits, and enforce community pet policies.',
    steps: [
      { title: 'Collect pet registration form', text: 'Have resident complete the pet registration form with breed, weight, vaccination records, and photo.' },
      { title: 'Verify breed and weight compliance', text: 'Check against the community pet policy for restricted breeds and weight limits.' },
      { title: 'Process pet deposit', text: 'Collect the one-time pet deposit ($300) and monthly pet rent ($35/mo). Update billing.' },
      { title: 'Issue pet tag', text: 'Provide a community pet identification tag. Record the tag number in the system.' },
      { title: 'Review pet rules with resident', text: 'Cover leash requirements, waste cleanup policy, designated pet areas, and noise expectations.' },
      { title: 'Add pet to resident file', text: 'Upload registration, vaccination records, and photo to the resident account.' },
    ],
    edgeCases: [
      { title: 'Emotional support animal', description: 'ESA requests are handled separately under fair housing. No pet deposit or rent. Require valid ESA letter.' },
      { title: 'Aggressive behavior report', description: 'Document the incident. Issue warning to owner. Second offense may require pet removal per lease.' },
    ],
    escalation: { when: 'If resident claims ESA status or pet causes injury to another resident', who: 'Community Manager (555-0103)' },
    contacts: [
      { role: 'Community Manager', name: 'David Kim', department: 'Resident Support', description: 'Pet policy enforcement and ESA requests' },
    ],
    referenceMaterials: [
      { title: 'Pet registration form', fileUrl: '/files/pet-registration.pdf' },
      { title: 'Pet policy document', fileUrl: '/files/pet-policy.pdf' },
    ],
  },
  {
    id: '11',
    title: 'HVAC System Seasonal Changeover',
    category: 'Operations',
    tags: ['HVAC', 'Seasonal', 'Preventive'],
    lastUpdated: 'Updated 2 weeks ago',
    overview: 'Execute the biannual HVAC changeover between heating and cooling modes for all buildings.',
    steps: [
      { title: 'Schedule changeover window', text: 'Coordinate with weather forecast for a 3-day mild period. Notify residents 1 week in advance.' },
      { title: 'Shut down current mode', text: 'Power down heating (or cooling) systems building by building. Allow 4-hour cooldown period.' },
      { title: 'Inspect and replace filters', text: 'Check all air handler filters. Replace any that are dirty or past 90-day mark.' },
      { title: 'Test new mode activation', text: 'Activate heating (or cooling) in each building. Verify thermostats are responding and airflow is correct.' },
      { title: 'Spot-check occupied units', text: 'Visit 10% of units to confirm temperature is within the target range (68-72°F heating, 72-76°F cooling).' },
      { title: 'Log completion', text: 'Record changeover date, buildings completed, any issues found, and filter inventory used.' },
      { title: 'Send resident confirmation', text: 'Email all residents confirming the changeover is complete and how to adjust their thermostats.' },
    ],
    edgeCases: [
      { title: 'Unit not reaching target temp', description: 'Dispatch technician for individual unit inspection. Check dampers and thermostat calibration.' },
      { title: 'Unexpected cold snap during cooling mode', description: 'Emergency protocol: can enable auxiliary heating without full changeover.' },
    ],
    escalation: { when: 'If more than 5% of units report HVAC issues within 48 hours of changeover', who: 'Facilities Director (555-0109)' },
    contacts: [
      { role: 'HVAC Contractor', name: 'Pacific Air Systems', department: 'Vendor', description: 'Complex HVAC repairs and parts' },
      { role: 'Facilities Director', name: 'Robert Nguyen', department: 'Operations', description: 'Building systems oversight' },
    ],
    referenceMaterials: [
      { title: 'HVAC changeover checklist', fileUrl: '/files/hvac-changeover.pdf' },
      { title: 'Filter inventory tracker', fileUrl: '/files/filter-inventory.xlsx' },
    ],
  },
  {
    id: '12',
    title: 'Security Incident Report',
    category: 'Operations',
    tags: ['Security', 'Incident', 'Safety'],
    lastUpdated: 'Updated 6 days ago',
    overview: 'Document and respond to security incidents including theft, vandalism, trespassing, and suspicious activity.',
    steps: [
      { title: 'Ensure safety of all persons', text: 'If there is an active threat, call 911 first. Evacuate the area if necessary.' },
      { title: 'Document the incident', text: 'Complete the security incident report form with date, time, location, persons involved, and description of events.' },
      { title: 'Collect evidence', text: 'Pull security camera footage for the relevant time window. Save a copy to the incident file.' },
      { title: 'Notify management', text: 'Email the property manager and security supervisor within 1 hour of the incident.' },
      { title: 'File police report if applicable', text: 'For theft, assault, or vandalism, assist the victim in filing a police report. Record the case number.' },
      { title: 'Communicate with residents', text: 'If the incident affects the community, send a factual, non-alarming notice to residents within 24 hours.' },
    ],
    edgeCases: [
      { title: 'Incident involves a minor', description: 'Contact parents/guardians immediately. Follow mandatory reporting requirements.' },
      { title: 'Media inquiry', description: 'Do not speak to media. Refer all inquiries to the corporate communications team.' },
    ],
    escalation: { when: 'If incident involves serious injury, weapon, or property damage over $5,000', who: 'Regional VP (555-0110)' },
    contacts: [
      { role: 'Security Supervisor', name: 'Frank Torres', department: 'Security', description: 'On-site security operations' },
      { role: 'Insurance Coordinator', name: 'Patricia Adams', department: 'Finance', description: 'Claims and liability' },
    ],
    referenceMaterials: [
      { title: 'Incident report form', fileUrl: '/files/incident-report.pdf' },
      { title: 'Camera system access guide', fileUrl: '/files/camera-guide.pdf' },
    ],
  },
  {
    id: '13',
    title: 'Resident Move-Out and Deposit Return',
    category: 'Leasing',
    tags: ['Move-Out', 'Deposits', 'Turnover'],
    lastUpdated: 'Updated 4 days ago',
    overview: 'Process resident move-outs including final inspection, deposit accounting, and unit turnover preparation.',
    steps: [
      { title: 'Confirm move-out date', text: 'Verify 30-day notice was provided per lease terms. Schedule move-out inspection.' },
      { title: 'Conduct move-out inspection', text: 'Walk the unit with the inspection checklist. Compare against move-in photos. Document all damage beyond normal wear.' },
      {
        title: 'Calculate deposit deductions',
        text: 'Itemize charges for damages, cleaning, and any unpaid rent or fees.',
        script: 'Deposit Accounting\n\nOriginal Deposit: $___\n\nDeductions:\n- Cleaning: $___\n- Paint/patch: $___\n- Carpet: $___\n- Other: $___\n\nTotal Deductions: $___\nRefund Amount: $___',
      },
      { title: 'Send itemized statement', text: 'Mail the itemized deposit statement and refund check within 21 days per state law.' },
      { title: 'Initiate unit turnover', text: 'Create a turnover work order for cleaning, painting, repairs, and carpet replacement as needed.' },
      { title: 'Update vacancy records', text: 'Mark the unit as vacant in the system. Update the availability list for the leasing team.' },
    ],
    edgeCases: [
      { title: 'Resident disputes deductions', description: 'Provide photos and documentation. Offer to schedule a re-inspection. Escalate to manager if unresolved.' },
      { title: 'Abandoned belongings', description: 'Follow state-mandated abandoned property procedures. Store items for required period before disposal.' },
    ],
    escalation: { when: 'If deposit dispute exceeds $500 or resident threatens legal action', who: 'Leasing Director (555-0105)' },
    contacts: [
      { role: 'Leasing Director', name: 'Maria Santos', department: 'Leasing', description: 'Deposit disputes and legal referrals' },
      { role: 'Turnover Coordinator', name: 'Alex Petrov', department: 'Operations', description: 'Unit make-ready scheduling' },
    ],
    referenceMaterials: [
      { title: 'Move-out inspection form', fileUrl: '/files/move-out-inspection.pdf' },
      { title: 'Deposit accounting template', fileUrl: '/files/deposit-accounting.xlsx' },
    ],
  },
  {
    id: '14',
    title: 'Water Leak Response',
    category: 'Operations',
    tags: ['Urgent', 'Plumbing', 'Water Damage'],
    lastUpdated: 'Updated 1 day ago',
    overview: 'Respond to water leaks to minimize damage, protect resident belongings, and restore service.',
    steps: [
      { title: 'Identify the source', text: 'Determine if the leak is from plumbing, roof, HVAC condensation, or external source.' },
      { title: 'Shut off water if needed', text: 'For major plumbing leaks, shut off the water supply to the affected area. Know your shutoff valve locations.' },
      { title: 'Mitigate immediate damage', text: 'Place buckets, towels, or wet-vac to contain water. Move resident belongings away from the affected area.' },
      { title: 'Contact restoration vendor', text: 'For significant water damage, call the preferred water restoration vendor within 1 hour to prevent mold growth.' },
      { title: 'Document damage', text: 'Take photos and video of all damage before and during cleanup. File an insurance claim if needed.' },
      { title: 'Communicate with affected residents', text: 'Provide timeline for repair and any temporary accommodations if the unit is uninhabitable.' },
      { title: 'Schedule follow-up inspection', text: 'Inspect the area 48-72 hours later for moisture levels and mold signs.' },
    ],
    edgeCases: [
      { title: 'Leak from unit above', description: 'Access the source unit. If resident is unavailable, use emergency access per lease terms.' },
      { title: 'Mold discovered', description: 'Isolate the area. Do not attempt cleanup. Contact certified mold remediation vendor.' },
    ],
    escalation: { when: 'If water damage affects multiple units or mold is discovered', who: 'Facilities Director (555-0109)' },
    contacts: [
      { role: 'Restoration Vendor', name: 'ServiceMaster', department: 'Vendor', description: '24/7 water damage restoration', phone: '555-0120' },
      { role: 'Insurance Coordinator', name: 'Patricia Adams', department: 'Finance', description: 'Property damage claims' },
    ],
    referenceMaterials: [
      { title: 'Water shutoff valve map', fileUrl: '/files/shutoff-valves.pdf' },
      { title: 'Vendor emergency contacts', fileUrl: '/files/vendor-contacts.pdf' },
    ],
  },
  {
    id: '15',
    title: 'Rent Concession Processing',
    category: 'Finance',
    tags: ['Concessions', 'Billing', 'Promotions'],
    lastUpdated: 'Updated 5 days ago',
    overview: 'Apply approved rent concessions to resident accounts, including move-in specials, retention offers, and hardship adjustments.',
    steps: [
      { title: 'Verify concession approval', text: 'Confirm the concession has been approved by the appropriate authority per the concession matrix.' },
      { title: 'Determine concession type', text: 'Identify whether it is a one-time credit, recurring monthly discount, or free rent period.' },
      {
        title: 'Apply concession in billing system',
        text: 'Enter the concession with the correct code and effective dates.',
        script: 'Billing → Concessions → New\nResident: [Name / Unit]\nType: [One-Time / Recurring / Free Rent]\nAmount: $___\nStart Date: ___\nEnd Date: ___\nApproval Code: ___',
      },
      { title: 'Notify resident', text: 'Send confirmation email with concession details, effective dates, and any conditions.' },
      { title: 'Document in resident file', text: 'Upload the signed concession agreement and approval documentation to the resident record.' },
    ],
    edgeCases: [
      { title: 'Concession exceeds authority level', description: 'Route to the next approval tier. Do not apply until all approvals are received.' },
    ],
    escalation: { when: 'If concession total exceeds $2,000 or applies to more than 3 months', who: 'Controller (555-0107)' },
    contacts: [
      { role: 'Accounting Manager', name: 'Lisa Wang', department: 'Finance', description: 'Concession approvals and audit' },
    ],
    referenceMaterials: [
      { title: 'Concession approval matrix', fileUrl: '/files/concession-matrix.pdf' },
    ],
  },
  {
    id: '16',
    title: 'Fire Alarm Response',
    category: 'Operations',
    tags: ['Safety', 'Emergency', 'Fire'],
    lastUpdated: 'Updated 3 days ago',
    overview: 'Respond to fire alarm activations including evacuation, fire department coordination, and system reset.',
    steps: [
      { title: 'Assess the alarm', text: 'Check the fire panel for the zone and device that triggered the alarm. Do not silence until investigated.' },
      { title: 'Investigate the source', text: 'Send staff to the indicated zone to check for visible smoke, fire, or a false alarm cause (cooking, dust, etc.).' },
      { title: 'Initiate evacuation if needed', text: 'If fire or smoke is confirmed, activate building evacuation. Guide residents to designated assembly points.' },
      { title: 'Contact fire department', text: 'Call 911 for any confirmed fire. For monitored systems, confirm the monitoring company has dispatched.' },
      { title: 'Document the incident', text: 'Record alarm time, cause, response actions, and fire department case number if applicable.' },
      { title: 'Reset the system', text: 'After clearance from the fire department (or confirmation of false alarm), reset the fire panel and silence alarms.' },
      { title: 'Notify residents', text: 'Send an all-clear notice explaining the cause and any follow-up actions.' },
    ],
    edgeCases: [
      { title: 'Repeated false alarms', description: 'Schedule system inspection. Check for faulty detectors. May need to replace units in affected areas.' },
      { title: 'Resident with mobility limitation', description: 'Maintain list of residents needing evacuation assistance. Assign buddy system.' },
    ],
    escalation: { when: 'Any confirmed fire or if system cannot be reset', who: 'Facilities Director (555-0109)' },
    contacts: [
      { role: 'Fire Monitoring Co.', name: 'Simplex Grinnell', department: 'Vendor', description: 'Fire alarm monitoring and service', phone: '555-0121' },
    ],
    referenceMaterials: [
      { title: 'Fire panel quick reference', fileUrl: '/files/fire-panel-guide.pdf' },
      { title: 'Evacuation route maps', fileUrl: '/files/evacuation-maps.pdf' },
    ],
  },
  {
    id: '17',
    title: 'Guest and Visitor Access',
    category: 'Resident Support',
    tags: ['Access', 'Security', 'Guests'],
    lastUpdated: 'Updated 1 week ago',
    overview: 'Manage guest access to the community including temporary passes, vendor access, and visitor parking.',
    steps: [
      { title: 'Verify resident authorization', text: 'Confirm the resident has submitted a guest authorization via the portal or front desk.' },
      { title: 'Issue temporary access', text: 'Provide the guest with a temporary access card or gate code. Set expiration per the authorization period.' },
      { title: 'Assign visitor parking', text: 'Direct guests to visitor parking areas. Issue a temporary parking permit if staying overnight.' },
      { title: 'Log the visit', text: 'Record guest name, resident unit, arrival time, and expected departure in the visitor log.' },
      { title: 'Collect access card on departure', text: 'Retrieve the temporary card when the guest leaves. Deactivate the access code.' },
    ],
    edgeCases: [
      { title: 'Guest arrives without authorization', description: 'Contact the resident to confirm. If resident is unreachable, guest must wait or return when authorization is provided.' },
    ],
    escalation: { when: 'If unauthorized person refuses to leave or resident reports unknown guest', who: 'Security Supervisor (555-0108)' },
    contacts: [
      { role: 'Front Desk Lead', name: 'Priya Sharma', department: 'Resident Support', description: 'Guest processing and visitor management' },
    ],
    referenceMaterials: [],
  },
  {
    id: '18',
    title: 'Amenity Reservation System',
    category: 'Resident Support',
    tags: ['Amenities', 'Reservations', 'Community'],
    lastUpdated: 'Updated 2 weeks ago',
    overview: 'Process resident reservations for shared amenities including the clubhouse, BBQ area, pool deck, and conference room.',
    steps: [
      { title: 'Receive reservation request', text: 'Accept request via online portal, email, or front desk. Collect date, time, amenity, and estimated guest count.' },
      { title: 'Check availability', text: 'Verify the amenity is not already booked. Check for any maintenance closures or community events.' },
      { title: 'Collect reservation fee', text: 'Process the refundable amenity deposit ($100 for clubhouse, $50 for other spaces) and any usage fees.' },
      { title: 'Confirm reservation', text: 'Send confirmation email with amenity rules, capacity limits, noise curfew, and cleanup expectations.' },
      { title: 'Post-event inspection', text: 'Inspect the amenity within 24 hours. Document condition and process deposit refund or deductions.' },
    ],
    edgeCases: [
      { title: 'Noise complaint during event', description: 'Remind resident of quiet hours. If violation continues, event may be shut down per community rules.' },
      { title: 'Damage to amenity', description: 'Document damage with photos. Deduct repair costs from deposit. Charge remainder to resident account.' },
    ],
    escalation: { when: 'If damage exceeds deposit amount or event violates community rules after warning', who: 'Community Manager (555-0103)' },
    contacts: [
      { role: 'Community Manager', name: 'David Kim', department: 'Resident Support', description: 'Amenity policy and event disputes' },
    ],
    referenceMaterials: [
      { title: 'Amenity reservation form', fileUrl: '/files/amenity-reservation.pdf' },
      { title: 'Amenity rules and fees', fileUrl: '/files/amenity-rules.pdf' },
    ],
  },
  {
    id: '19',
    title: 'Lease Violation Notice',
    category: 'Leasing',
    tags: ['Violations', 'Compliance', 'Enforcement'],
    lastUpdated: 'Updated 3 days ago',
    overview: 'Issue and track lease violation notices for breaches of community rules or lease terms.',
    steps: [
      { title: 'Document the violation', text: 'Record the specific lease clause violated, date, time, evidence, and any witness statements.' },
      { title: 'Verify violation history', text: 'Check the resident file for prior violations. Determine if this is a first offense or repeat.' },
      {
        title: 'Prepare the notice',
        text: 'Use the appropriate notice template based on violation type and severity.',
        script: 'Date: ___\nResident: ___\nUnit: ___\n\nViolation: [Description]\nLease Clause: Section ___\n\nThis is your [1st / 2nd / 3rd] notice.\n\nYou have [X] days to cure this violation.\n\nFailure to comply may result in further action up to and including lease termination.',
      },
      { title: 'Deliver the notice', text: 'Send via certified mail AND post on the door. Keep proof of delivery.' },
      { title: 'Set cure period reminder', text: 'Calendar the cure deadline. Plan a follow-up inspection on that date.' },
      { title: 'Follow up', text: 'Inspect on the cure date. If resolved, close the case. If not, escalate to the next step in the enforcement process.' },
    ],
    edgeCases: [
      { title: 'Resident claims they were unaware', description: 'Provide a copy of the lease section and community rules. The notice still stands.' },
      { title: 'Third violation', description: 'Initiate consultation with legal counsel for potential eviction proceedings.' },
    ],
    escalation: { when: 'If resident does not cure within the notice period or this is the third violation', who: 'Legal Counsel (555-0111)' },
    contacts: [
      { role: 'Legal Counsel', name: 'Jennifer Park', department: 'Legal', description: 'Eviction proceedings and legal compliance' },
    ],
    referenceMaterials: [
      { title: 'Violation notice templates', fileUrl: '/files/violation-templates.zip' },
      { title: 'Lease enforcement flowchart', fileUrl: '/files/enforcement-flow.pdf' },
    ],
  },
  {
    id: '20',
    title: 'Utility Billing Reconciliation',
    category: 'Finance',
    tags: ['Utilities', 'Billing', 'RUBS'],
    lastUpdated: 'Updated 1 week ago',
    overview: 'Reconcile monthly utility bills and allocate charges to individual units using the RUBS (Ratio Utility Billing System) method.',
    steps: [
      { title: 'Collect utility invoices', text: 'Gather all utility bills (water, gas, electric, trash) for the billing period from each provider.' },
      { title: 'Enter total amounts', text: 'Input the total utility costs into the RUBS calculation spreadsheet by category.' },
      { title: 'Run allocation calculation', text: 'The system allocates costs based on unit square footage, occupant count, and usage factors.' },
      { title: 'Review for anomalies', text: 'Check for any unit charges that seem unusually high or low compared to the prior month (>20% variance).' },
      { title: 'Post charges to resident accounts', text: 'Upload the allocation file to the billing system. Verify charges appear on next month statements.' },
      { title: 'Handle disputes', text: 'If a resident questions their utility charge, provide the calculation methodology and their specific factors.' },
    ],
    edgeCases: [
      { title: 'Vacant unit allocation', description: 'Vacant units absorb their proportional share. Owner/management covers these costs.' },
      { title: 'Utility rate increase', description: 'Notify residents 30 days before the new rate takes effect per RUBS disclosure requirements.' },
    ],
    escalation: { when: 'If utility costs increase more than 15% month-over-month or resident threatens legal action', who: 'Controller (555-0107)' },
    contacts: [
      { role: 'Utility Coordinator', name: 'Nina Patel', department: 'Finance', description: 'Utility account management and RUBS' },
    ],
    referenceMaterials: [
      { title: 'RUBS calculation template', fileUrl: '/files/rubs-template.xlsx' },
      { title: 'Utility provider contacts', fileUrl: '/files/utility-providers.pdf' },
    ],
  },
  {
    id: '21',
    title: 'Pool and Spa Maintenance',
    category: 'Operations',
    tags: ['Amenities', 'Maintenance', 'Seasonal'],
    lastUpdated: 'Updated 2 weeks ago',
    overview: 'Maintain pool and spa facilities including daily chemical testing, cleaning, and seasonal opening/closing.',
    steps: [
      { title: 'Test water chemistry', text: 'Test pH (7.2-7.6), chlorine (1-3 ppm), and alkalinity (80-120 ppm) twice daily using the test kit.' },
      { title: 'Adjust chemicals as needed', text: 'Add chlorine, pH adjuster, or shock treatment based on test results. Record all additions in the chemical log.' },
      { title: 'Clean and vacuum', text: 'Skim debris, brush walls, vacuum floor, and clean skimmer baskets. Empty robot cleaner if applicable.' },
      { title: 'Inspect equipment', text: 'Check pump, filter pressure, heater operation, and automatic chlorinator levels.' },
      { title: 'Update log and signage', text: 'Record all readings in the pool log. Ensure posted rules and emergency signs are intact.' },
    ],
    edgeCases: [
      { title: 'Water quality failure', description: 'Close pool immediately. Post closure sign. Super-chlorinate and retest in 24 hours before reopening.' },
      { title: 'Injury at pool', description: 'Administer first aid. Call 911 if serious. Complete incident report. Close pool if unsafe condition exists.' },
    ],
    escalation: { when: 'If pool must be closed for more than 24 hours or health department is involved', who: 'Facilities Director (555-0109)' },
    contacts: [
      { role: 'Pool Service Vendor', name: 'Blue Wave Pools', department: 'Vendor', description: 'Equipment repair and chemical supply', phone: '555-0122' },
    ],
    referenceMaterials: [
      { title: 'Chemical testing log', fileUrl: '/files/pool-log.xlsx' },
      { title: 'Pool equipment manual', fileUrl: '/files/pool-equipment.pdf' },
    ],
  },
  {
    id: '22',
    title: 'Resident Transfer Between Units',
    category: 'Leasing',
    tags: ['Transfers', 'Relocation'],
    lastUpdated: 'Updated 6 days ago',
    overview: 'Process resident requests to transfer to a different unit within the community, including lease amendment and logistics.',
    steps: [
      { title: 'Evaluate transfer request', text: 'Review the reason for transfer, current lease status, and available units that meet the request.' },
      { title: 'Approve or deny the transfer', text: 'Check resident account for good standing (no unpaid balance, no active violations). Manager approval required.' },
      { title: 'Prepare lease amendment', text: 'Draft the transfer addendum with new unit, rent amount, effective date, and any transfer fee.' },
      { title: 'Schedule the move', text: 'Coordinate move date, elevator reservation (if applicable), and key exchange timing.' },
      { title: 'Conduct inspections', text: 'Complete move-out inspection of old unit and move-in inspection of new unit on the same day.' },
      { title: 'Update all records', text: 'Update unit assignment, parking, mailbox, access cards, and billing in all systems.' },
    ],
    edgeCases: [
      { title: 'Transfer due to maintenance issue', description: 'If transfer is necessitated by uninhabitable conditions, waive transfer fee and offer rent concession.' },
      { title: 'Resident changes mind after signing', description: 'Transfer addendum has a 48-hour rescission period. After that, transfer fee is non-refundable.' },
    ],
    escalation: { when: 'If transfer is due to harassment, safety concern, or ADA accommodation', who: 'Leasing Director (555-0105)' },
    contacts: [
      { role: 'Leasing Coordinator', name: 'Samantha Cole', department: 'Leasing', description: 'Unit transfers and lease amendments' },
    ],
    referenceMaterials: [
      { title: 'Transfer request form', fileUrl: '/files/transfer-request.pdf' },
      { title: 'Transfer addendum template', fileUrl: '/files/transfer-addendum.docx' },
    ],
  },
  {
    id: '23',
    title: 'Annual Budget Preparation',
    category: 'Finance',
    tags: ['Budget', 'Planning', 'Annual'],
    lastUpdated: 'Updated 3 weeks ago',
    overview: 'Prepare the annual operating budget for the property including revenue projections, expense forecasts, and capital improvement planning.',
    steps: [
      { title: 'Review prior year actuals', text: 'Pull financial reports for the trailing 12 months. Identify trends, variances, and one-time expenses.' },
      { title: 'Forecast revenue', text: 'Project rental income based on current occupancy, scheduled rent increases, and market comps.' },
      { title: 'Estimate operating expenses', text: 'Budget each expense category (payroll, utilities, maintenance, insurance, taxes) using historical data and known increases.' },
      { title: 'Plan capital expenditures', text: 'Identify major capital projects (roof, HVAC, paving, etc.) based on the capital improvement schedule and property condition report.' },
      { title: 'Compile and review with management', text: 'Assemble the draft budget package. Present to the regional manager and ownership for review.' },
      { title: 'Incorporate feedback and finalize', text: 'Make requested adjustments. Obtain final approval signatures. Distribute to department heads.' },
      { title: 'Load budget into accounting system', text: 'Enter the approved budget line items into the financial system for monthly variance tracking.' },
      { title: 'Communicate to team', text: 'Hold a team meeting to review budget goals, spending authority, and any changes from prior year.' },
    ],
    edgeCases: [
      { title: 'Major unplanned capital expense', description: 'Request a budget amendment. Requires ownership approval for items over $25,000 not in the original budget.' },
    ],
    escalation: { when: 'If projected NOI falls below ownership target or budget is rejected', who: 'Regional VP (555-0110)' },
    contacts: [
      { role: 'Controller', name: 'Margaret Chen', department: 'Finance', description: 'Budget review and financial reporting' },
      { role: 'Regional VP', name: 'Richard Blake', department: 'Corporate', description: 'Budget approval and ownership liaison' },
    ],
    referenceMaterials: [
      { title: 'Budget template', fileUrl: '/files/budget-template.xlsx' },
      { title: 'Prior year financials', fileUrl: '/files/prior-year-actuals.pdf' },
      { title: 'Capital improvement schedule', fileUrl: '/files/capital-schedule.pdf' },
    ],
  },
  {
    id: '24',
    title: 'Landscaping and Grounds Maintenance',
    category: 'Operations',
    tags: ['Grounds', 'Landscaping', 'Curb Appeal'],
    lastUpdated: 'Updated 5 days ago',
    overview: 'Oversee landscaping vendor performance and maintain grounds including irrigation, seasonal planting, and tree care.',
    steps: [
      { title: 'Conduct weekly grounds walk', text: 'Walk the entire property weekly to identify landscaping needs, dead plants, irrigation issues, and trip hazards.' },
      { title: 'Submit work orders for issues', text: 'Log any deficiencies in the maintenance system. Tag as vendor-responsible or in-house repair.' },
      { title: 'Review vendor service report', text: 'Check the landscaping vendor weekly report for completed tasks, chemical applications, and upcoming scheduled work.' },
      { title: 'Coordinate seasonal projects', text: 'Plan spring planting, summer irrigation adjustments, fall cleanup, and winter prep with the vendor.' },
      { title: 'Inspect completed work', text: 'Walk with the vendor after major projects to confirm quality standards are met before signing off.' },
    ],
    edgeCases: [
      { title: 'Tree down or limb hazard', description: 'Rope off the area immediately. Contact emergency tree service. File insurance claim if property damage occurred.' },
      { title: 'Irrigation system failure', description: 'Shut off affected zone. Contact irrigation vendor for emergency repair to prevent water waste and plant loss.' },
    ],
    escalation: { when: 'If vendor consistently underperforms or safety hazard exists on grounds', who: 'Operations Director (555-0106)' },
    contacts: [
      { role: 'Landscaping Vendor', name: 'GreenScape Inc.', department: 'Vendor', description: 'Weekly grounds maintenance and seasonal projects', phone: '555-0123' },
    ],
    referenceMaterials: [
      { title: 'Grounds inspection checklist', fileUrl: '/files/grounds-checklist.pdf' },
    ],
  },
  {
    id: '25',
    title: 'Elevator Maintenance and Outage',
    category: 'Operations',
    tags: ['Elevator', 'Maintenance', 'Safety'],
    lastUpdated: 'Updated 2 days ago',
    overview: 'Manage elevator maintenance schedules and respond to elevator outages or entrapments.',
    steps: [
      { title: 'Monitor maintenance schedule', text: 'Verify the elevator vendor completes monthly preventive maintenance per the service contract.' },
      { title: 'Respond to outage report', text: 'When an outage is reported, check if anyone is trapped. If so, call 911 and the elevator vendor emergency line immediately.' },
      { title: 'Post outage notice', text: 'Place "Out of Service" signs on all floors. Email affected residents with estimated repair time.' },
      { title: 'Coordinate with vendor', text: 'Contact the elevator service company for repair dispatch. Track ETA and communicate updates to residents.' },
      { title: 'Assist residents with mobility needs', text: 'Contact residents on the ADA accommodation list. Arrange assistance or alternative access as needed.' },
      { title: 'Verify repair completion', text: 'After repair, ride the elevator to all floors to confirm proper operation before removing out-of-service signs.' },
      { title: 'Document the incident', text: 'Record outage duration, cause, repair performed, and cost. Update the elevator maintenance log.' },
    ],
    edgeCases: [
      { title: 'Person trapped in elevator', description: 'Call 911 first. Communicate with the trapped person via intercom. Do NOT attempt to force doors open.' },
      { title: 'Extended outage (>24 hours)', description: 'Arrange temporary housing or alternative access for residents with mobility limitations.' },
    ],
    escalation: { when: 'If entrapment occurs, outage exceeds 24 hours, or inspection fails', who: 'Facilities Director (555-0109)' },
    contacts: [
      { role: 'Elevator Vendor', name: 'Otis Elevator Co.', department: 'Vendor', description: '24/7 elevator service and repair', phone: '555-0124' },
      { role: 'Facilities Director', name: 'Robert Nguyen', department: 'Operations', description: 'Building systems and vendor oversight' },
    ],
    referenceMaterials: [
      { title: 'Elevator service contract', fileUrl: '/files/elevator-contract.pdf' },
      { title: 'Elevator entrapment procedure', fileUrl: '/files/entrapment-procedure.pdf' },
    ],
  },
];
